object ControlForm_Accounting: TControlForm_Accounting
  Left = 0
  Top = 0
  Caption = 'ControlForm_Accounting'
  ClientHeight = 207
  ClientWidth = 268
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object MAIN_DOCK_PANEL: TScrollBox
    Left = 0
    Top = 0
    Width = 268
    Height = 207
    Align = alClient
    BevelInner = bvNone
    BevelOuter = bvNone
    BevelKind = bkFlat
    BorderStyle = bsNone
    Color = clWhite
    ParentColor = False
    TabOrder = 0
    ExplicitLeft = -9
    ExplicitTop = -9
    ExplicitWidth = 277
    ExplicitHeight = 216
  end
end
