object AvoBase_BaseForm_Menu: TAvoBase_BaseForm_Menu
  Left = 340
  Top = 9
  BorderIcons = []
  BorderStyle = bsSingle
  BorderWidth = 1
  Caption = 'AvoBase_BaseForm_Menu'
  ClientHeight = 255
  ClientWidth = 413
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object BASEFORM_DOCK: TPanel
    Left = 0
    Top = 0
    Width = 413
    Height = 255
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 1
    Color = clNavy
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 578
    ExplicitHeight = 482
    object BASEFORM_BACK_PANEL: TPanel
      Left = 1
      Top = 1
      Width = 411
      Height = 253
      Align = alClient
      BevelOuter = bvNone
      Caption = 'BASEFORM_BACK_PANEL'
      Color = clWhite
      ParentBackground = False
      TabOrder = 0
      ExplicitWidth = 576
      ExplicitHeight = 480
      object BASE_FORM_TOP_PANEL: TPanel
        Left = 0
        Top = 0
        Width = 411
        Height = 20
        Align = alTop
        BevelOuter = bvNone
        Color = clGray
        ParentBackground = False
        TabOrder = 0
        ExplicitWidth = 576
        object BASE_FORM_CAPTION_LABEL: TLabel
          Left = 6
          Top = 0
          Width = 405
          Height = 20
          Align = alClient
          Caption = 'BASE_FORM_CAPTION_LABEL'
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -15
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentColor = False
          ParentFont = False
          Transparent = True
          ExplicitWidth = 256
          ExplicitHeight = 18
        end
        object BASE_LABEL_SEP_PANEL: TPanel
          Left = 0
          Top = 0
          Width = 6
          Height = 20
          Align = alLeft
          BevelOuter = bvNone
          ParentColor = True
          TabOrder = 0
        end
      end
      object BASE_DOCK_PANEL: TPanel
        Left = 0
        Top = 74
        Width = 411
        Height = 158
        Align = alClient
        BevelOuter = bvNone
        BorderWidth = 1
        Caption = 'BASE_DOCK_PANEL'
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 1
        ExplicitWidth = 576
        ExplicitHeight = 385
      end
      object ToolBar: TToolBar
        Left = 0
        Top = 20
        Width = 411
        Height = 54
        AutoSize = True
        ButtonHeight = 50
        ButtonWidth = 65
        Caption = 'ToolBar'
        Color = clWhite
        DisabledImages = IMG_StorageForm.Disable_Img
        EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
        EdgeInner = esNone
        EdgeOuter = esNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        HotTrackColor = clGreen
        Images = IMG_StorageForm.Avobase_ToolBar_Img
        ParentColor = False
        ParentFont = False
        ShowCaptions = True
        TabOrder = 2
        Transparent = False
        Wrapable = False
        OnCustomDraw = ToolBarCustomDraw
        ExplicitWidth = 576
      end
      object StatusBar: TStatusBar
        Left = 0
        Top = 232
        Width = 411
        Height = 21
        Panels = <
          item
            Width = 50
          end>
        ExplicitTop = 459
        ExplicitWidth = 576
      end
    end
  end
end
