object AvoBase_BaseForm_Select: TAvoBase_BaseForm_Select
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsSingle
  Caption = 'AvoBase_BaseForm_Select'
  ClientHeight = 428
  ClientWidth = 614
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object BASE_BACK_PANEL: TPanel
    Left = 0
    Top = 0
    Width = 614
    Height = 428
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 1
    Color = clNavy
    ParentBackground = False
    TabOrder = 0
    ExplicitWidth = 610
    ExplicitHeight = 382
    object BASE_FORM_TOP_PANEL: TPanel
      Left = 1
      Top = 1
      Width = 612
      Height = 20
      Align = alTop
      BevelOuter = bvNone
      Color = clGray
      ParentBackground = False
      TabOrder = 0
      ExplicitWidth = 608
      object BASE_FORM_CAPTION_LABEL: TLabel
        Left = 6
        Top = 0
        Width = 606
        Height = 20
        Align = alClient
        Caption = 'BASE_FORM_CAPTION_LABEL'
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -15
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentColor = False
        ParentFont = False
        Transparent = True
        ExplicitWidth = 256
        ExplicitHeight = 18
      end
      object BASE_LABEL_SEP_PANEL: TPanel
        Left = 0
        Top = 0
        Width = 6
        Height = 20
        Align = alLeft
        BevelOuter = bvNone
        ParentColor = True
        TabOrder = 0
      end
    end
    object StatusBar: TStatusBar
      Left = 1
      Top = 406
      Width = 612
      Height = 21
      Panels = <
        item
          Width = 50
        end>
      ExplicitTop = 360
      ExplicitWidth = 608
    end
    object BASE_NAVBAR_PANEL: TPanel
      Left = 1
      Top = 21
      Width = 612
      Height = 56
      Align = alTop
      BevelOuter = bvNone
      Color = clWhite
      ParentBackground = False
      TabOrder = 2
      ExplicitWidth = 608
      object BASE_NAVBAR_DOCK_PANEL: TPanel
        Left = 460
        Top = 0
        Width = 152
        Height = 56
        Align = alRight
        BevelOuter = bvNone
        Caption = 'BASE_NAVBAR_DOCK_PANEL'
        Ctl3D = False
        ParentCtl3D = False
        TabOrder = 0
        ExplicitLeft = 456
      end
      object ToolBar: TToolBar
        Left = 0
        Top = 0
        Width = 226
        Height = 56
        Align = alLeft
        AutoSize = True
        ButtonHeight = 50
        ButtonWidth = 65
        Caption = 'ToolBar'
        Color = clWhite
        DisabledImages = IMG_StorageForm.Disable_Img
        EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
        EdgeInner = esNone
        EdgeOuter = esNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        HotTrackColor = clGreen
        Images = IMG_StorageForm.Avobase_ToolBar_Img
        ParentColor = False
        ParentFont = False
        ShowCaptions = True
        TabOrder = 1
        Transparent = False
        Wrapable = False
      end
    end
    object BASE_LIST_DOCK_PANEL: TPanel
      Left = 1
      Top = 118
      Width = 612
      Height = 288
      Align = alClient
      BevelOuter = bvNone
      BorderWidth = 1
      Caption = 'BASE_LIST_DOCK_PANEL'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 3
      ExplicitWidth = 608
      ExplicitHeight = 242
    end
    object OPTION_DOCK: TPanel
      Left = 1
      Top = 77
      Width = 612
      Height = 41
      Align = alTop
      BevelOuter = bvNone
      Caption = 'OPTION_DOCK'
      Color = clWhite
      DragCursor = crHandPoint
      ParentBackground = False
      TabOrder = 4
      ExplicitWidth = 608
    end
  end
end
