object CustOrd_CustForm: TCustOrd_CustForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'CustOrd_CustForm'
  ClientHeight = 169
  ClientWidth = 767
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object BASEFORM_DOCK: TPanel
    Left = 0
    Top = 0
    Width = 767
    Height = 169
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 1
    Color = clNavy
    ParentBackground = False
    TabOrder = 0
    object BASEFORM_BACK_PANEL: TPanel
      Left = 1
      Top = 1
      Width = 765
      Height = 167
      Align = alClient
      BevelOuter = bvNone
      Caption = 'BASEFORM_BACK_PANEL'
      Color = clWhite
      ParentBackground = False
      TabOrder = 0
      object BASE_FORM_TOP_PANEL: TPanel
        Left = 0
        Top = 0
        Width = 765
        Height = 20
        Align = alTop
        BevelOuter = bvNone
        Color = 16094334
        ParentBackground = False
        TabOrder = 0
        object BASE_FORM_CAPTION_LABEL: TLabel
          Left = 6
          Top = 0
          Width = 759
          Height = 20
          Align = alClient
          Caption = 'BASE_FORM_CAPTION_LABEL'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -15
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentColor = False
          ParentFont = False
          Transparent = True
          ExplicitWidth = 256
          ExplicitHeight = 18
        end
        object BASE_LABEL_SEP_PANEL: TPanel
          Left = 0
          Top = 0
          Width = 6
          Height = 20
          Align = alLeft
          BevelOuter = bvNone
          ParentColor = True
          TabOrder = 0
        end
      end
      object BASE_DOCK_PANEL: TPanel
        Left = 0
        Top = 70
        Width = 765
        Height = 76
        Align = alClient
        BevelOuter = bvNone
        BorderWidth = 1
        Caption = 'PRODUCT_DOCK_PANEL'
        Color = clWhite
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 1
      end
      object ToolBar: TToolBar
        Left = 0
        Top = 20
        Width = 765
        Height = 50
        AutoSize = True
        ButtonHeight = 50
        ButtonWidth = 65
        Caption = 'ToolBar'
        Color = clWhite
        DisabledImages = IMG_StorageForm.Disable_Img
        EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
        EdgeInner = esNone
        EdgeOuter = esNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        HotTrackColor = clGreen
        Images = IMG_StorageForm.Avobase_ToolBar_Img
        ParentColor = False
        ParentFont = False
        ShowCaptions = True
        TabOrder = 2
        Transparent = False
        Wrapable = False
      end
      object StatusBar: TStatusBar
        Left = 0
        Top = 146
        Width = 765
        Height = 21
        Panels = <
          item
            Width = 50
          end>
      end
    end
  end
end
