object ControlForm_Report: TControlForm_Report
  Left = 0
  Top = 0
  Caption = 'ControlForm_Report'
  ClientHeight = 173
  ClientWidth = 280
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object MAIN_DOCK_PANEL: TScrollBox
    Left = 0
    Top = 0
    Width = 280
    Height = 173
    Align = alClient
    BevelInner = bvNone
    BevelOuter = bvNone
    BevelKind = bkFlat
    BorderStyle = bsNone
    Color = clWhite
    ParentColor = False
    TabOrder = 0
  end
end
